### ISSUE TITLE
ExperimentalAcrylicBorder (Material) causes a NullReferenceException

### ISSUE THREAD

**Issue by PerfectlyFineCode** [Kir-Antipov/HotAvalonia#12]
### Version:
Library version: 1.1.1
AvaloniaUI Version: 11.1.3

### Source
```xml
   <Panel>
         <ExperimentalAcrylicBorder IsHitTestVisible="False"> 
             <ExperimentalAcrylicBorder.Material> 
                 <ExperimentalAcrylicMaterial 
                     BackgroundSource="Digger"
                     MaterialOpacity="0.8"
                     TintColor="Black"
                     TintOpacity="1" />
             </ExperimentalAcrylicBorder.Material>
         </ExperimentalAcrylicBorder>
    </Panel>
```

### Error

```csharp
[HotReload]Failed to reload 'ExtendedDesktop.Views.OptionsWindow' ('avares://ExtendedDesktop/Views/OptionsWindow.axaml'): 'System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Controls.ExperimentalAcrylicBorder.SyncMaterial(CompositionVisual visual)
   at Avalonia.Controls.ExperimentalAcrylicBorder.CreateCompositionVisual(Compositor compositor)
   at Avalonia.Visual.AttachToCompositor(Compositor compositor)
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Input.InputElement.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Visual.SetVisualParent(Visual value)
   at Avalonia.Visual.SetVisualParent(IList children, Visual parent)
   at Avalonia.Visual.VisualChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(IList t, Int32 index)
   at Avalonia.Collections.AvaloniaList`1.InsertRange(Int32 index, IEnumerable`1 items)
   at Avalonia.Controls.Panel.ChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index)
   at Avalonia.Collections.AvaloniaList`1.Add(T item)
   at Builder_8267896ddabb41e49fd37a3417d4a899_avares___ExtendedDesktop_Views_OptionsWindow_axaml.__AvaloniaXamlIlPopulate(IServiceProvider, OptionsWindow)
   at lambda_method1(Closure, IServiceProvider, Object)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadOrPopulate(Type created, Object rootInstance, IServiceProvider parentServiceProvider)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.<>c.<LoadGroupSreCore>b__16_2(ValueTuple`2 t)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadGroupSreCore(IReadOnlyCollection`1 documents, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.AvaloniaRuntimeXamlLoader.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri, Boolean designMode)
   at Avalonia.Markup.Xaml.AvaloniaRuntimeXamlLoader.Load(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean designMode)
   at HotAvalonia.Helpers.AvaloniaControlHelper.Load(String xaml, Uri uri, Object control, MethodInfo& compiledPopulateMethod) in /_/src/HotAvalonia/Helpers/AvaloniaControlHelper.cs:line 48
   at HotAvalonia.AvaloniaControlInfo.Load(String xaml, Object control, MethodInfo& compiledPopulateMethod) in /_/src/HotAvalonia/AvaloniaControlInfo.cs:line 127
   at HotAvalonia.AvaloniaControlManager.ReloadAsync(String xaml, CancellationToken cancellationToken) in /_/src/HotAvalonia/AvaloniaControlManager.cs:line 93
   at HotAvalonia.AvaloniaControlManager.ReloadAsync(CancellationToken cancellationToken) in /_/src/HotAvalonia/AvaloniaControlManager.cs:line 76
   at HotAvalonia.AvaloniaHotReloadContext.OnChanged(Object sender, FileSystemEventArgs args) in /_/src/HotAvalonia/AvaloniaHotReloadContext.cs:line 112' (AvaloniaHotReloadContext #31842847)
   ```
   
   is this something that is fixable within the library or is this an issue with Avalonia itself?

**Comment by Kir-Antipov** [comment]
How peculiar!

> is this something that is fixable within the library or is this an issue with Avalonia itself?

Cannot tell at the moment, as I need to investigate it first.
