### ISSUE TITLE
Doesn't work with `<PublishAot>true</PublishAot>`

### ISSUE THREAD

**Issue by CoRS-Tech** [Kir-Antipov/HotAvalonia#16]
After updating to 2.0 and using .NET 9, 'EnableHotReload' produces the following exception:
```dart
System.TypeInitializationException: The type initializer for 'HotAvalonia.Helpers.AvaloniaControlHelper' threw an exception.
 ---> System.InvalidOperationException: Method injection is not available in the current runtime environment.
   at HotAvalonia.Reflection.Inject.MethodInjector.ThrowNotSupportedException() in /_/src/HotAvalonia/Reflection/Inject/MethodInjector.cs:line 71
   at HotAvalonia.Reflection.Inject.MethodInjector.ThrowIfNotSupported() in /_/src/HotAvalonia/Reflection/Inject/MethodInjector.cs:line 62
   at HotAvalonia.Reflection.Inject.CallbackInjector.ThrowIfNotSupported() in /_/src/HotAvalonia/Reflection/Inject/CallbackInjector.cs:line 26
   at HotAvalonia.Reflection.Inject.CallbackInjector.Inject(MethodBase target, MethodBase callback, Object thisArg) in /_/src/HotAvalonia/Reflection/Inject/CallbackInjector.cs:line 56
   at HotAvalonia.Reflection.Inject.CallbackInjector.Inject(MethodBase target, Delegate callback) in /_/src/HotAvalonia/Reflection/Inject/CallbackInjector.cs:line 33
   at HotAvalonia.Helpers.AvaloniaControlHelper..cctor() in /_/src/HotAvalonia/Helpers/AvaloniaControlHelper.cs:line 60
   --- End of inner exception stack trace ---
   at HotAvalonia.Helpers.AvaloniaControlHelper.TryInjectPopulateOverride(FieldInfo populateOverride, Action`2 populate, IInjection& injection) in /_/src/HotAvalonia/Helpers/AvaloniaControlHelper.cs:line 182
   at HotAvalonia.AvaloniaControlInfo.TryInjectPopulateOverride(Action`2 populate, IInjection& injection) in /_/src/HotAvalonia/AvaloniaControlInfo.cs:line 178
   at HotAvalonia.AvaloniaControlManager.TryInjectPopulateCallback(AvaloniaControlInfo controlInfo, Func`3 onPopulate, IInjection& injection) in /_/src/HotAvalonia/AvaloniaControlManager.cs:line 185
   at HotAvalonia.AvaloniaControlManager..ctor(AvaloniaControlInfo controlInfo, String fileName) in /_/src/HotAvalonia/AvaloniaControlManager.cs:line 54
   at HotAvalonia.<AvaloniaHotReloadContext>FE175869FAF7D7C5AA3B3E1E0D6C8D0FB6B623B28E34A613076134802E243266C__AvaloniaProjectHotReloadContext.ResolveControlManager(AvaloniaControlInfo controlInfo, String rootPath) in /_/src/HotAvalonia/AvaloniaHotReloadContext.cs:line 328
   at HotAvalonia.<AvaloniaHotReloadContext>FE175869FAF7D7C5AA3B3E1E0D6C8D0FB6B623B28E34A613076134802E243266C__AvaloniaProjectHotReloadContext.<>c__DisplayClass3_0.<.ctor>b__0(AvaloniaControlInfo x) in /_/src/HotAvalonia/AvaloniaHotReloadContext.cs:line 210
   at System.Linq.Enumerable.ArraySelectIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at HotAvalonia.<AvaloniaHotReloadContext>FE175869FAF7D7C5AA3B3E1E0D6C8D0FB6B623B28E34A613076134802E243266C__AvaloniaProjectHotReloadContext..ctor(String rootPath, IEnumerable`1 controls) in /_/src/HotAvalonia/AvaloniaHotReloadContext.cs:line 209
   at HotAvalonia.AvaloniaHotReloadContext.FromUnverifiedAssembly(Assembly assembly) in /_/src/HotAvalonia/AvaloniaHotReloadContext.cs:line 98
   at HotAvalonia.AvaloniaHotReloadContext.<>c.<FromAppDomain>b__3_0(AppDomain _, Assembly asm) in /_/src/HotAvalonia/AvaloniaHotReloadContext.cs:line 53
   at HotAvalonia.<IHotReloadContext>FFD67A1B8CF259EF6F4152BF5B50BCFF9B8BE44F0CF610B392C6F2E94FE204B95__AppDomainHotReloadContext.<.ctor>b__4_0(Assembly x) in /_/src/HotAvalonia/IHotReloadContext.cs:line 185
   at System.Linq.Enumerable.ArraySelectIterator`2.MoveNext()
   at System.Linq.Enumerable.IEnumerableWhereIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.IEnumerableWhereIterator`1.ToArray()
   at HotAvalonia.HotReloadContext.Combine(IEnumerable`1 contexts) in /_/src/HotAvalonia/IHotReloadContext.cs:line 82
   at HotAvalonia.<IHotReloadContext>FFD67A1B8CF259EF6F4152BF5B50BCFF9B8BE44F0CF610B392C6F2E94FE204B95__AppDomainHotReloadContext..ctor(AppDomain appDomain, Func`3 contextFactory) in /_/src/HotAvalonia/IHotReloadContext.cs:line 184
   at HotAvalonia.HotReloadContext.FromAppDomain(AppDomain appDomain, Func`3 contextFactory) in /_/src/HotAvalonia/IHotReloadContext.cs:line 50
   at HotAvalonia.AvaloniaHotReloadContext.FromAppDomain(AppDomain appDomain) in /_/src/HotAvalonia/AvaloniaHotReloadContext.cs:line 53
   at HotAvalonia.AvaloniaHotReloadContext.FromAppDomain() in /_/src/HotAvalonia/AvaloniaHotReloadContext.cs:line 37
   at HotAvalonia.AvaloniaHotReloadExtensions.EnableHotReload(Application app, String appFilePath)
   ```
   
![image](https://github.com/user-attachments/assets/0c34a744-b282-4769-9c23-19100f08e4ed)
The returned `InjectionType` will always be `InjectionType.None` in .NET 9 environments, unless `PlatformTriple.Current` does not throw an exception, which it does in my case. Is it game over for .NET 9 in this case?

**Comment by Kir-Antipov** [comment]
What OS and CPU architecture do you use?

**Comment by CoRS-Tech** [comment]
I debugged MonoMod and everything Arch, OS and runtime related was fine. This is the stack trace that it was throwing:
```
System.PlatformNotSupportedException: Dynamic code generation is not supported on this platform.
   at System.Reflection.Emit.AssemblyBuilder.ThrowDynamicCodeNotSupported()
   at System.Reflection.Emit.AssemblyBuilder.EnsureDynamicCodeSupported()
   at System.Reflection.Emit.DynamicMethod.Init(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] signature, Type owner, Module m, Boolean skipVisibility, Boolean transparentMethod)
   at System.Reflection.Emit.DynamicMethod..ctor(String name, Type returnType, Type[] parameterTypes, Type owner, Boolean skipVisibility)
   at MonoMod.Utils.DMDEmitDynamicMethodGenerator.GenerateCore(DynamicMethodDefinition dmd, Object context)
   ... more below omitted
   ```
This makes sense when publishing NativeAOT, because it does not have a JIT, so removing `<PublishAot>true</PublishAot>` fixed the issue. What is weird though is that in debug/run mode, the project is supposed to compile normally afaik, and not natively. Either way, I don't think this will be an issue for this library as it's a non-production dependency.

**Comment by Kir-Antipov** [comment]
Thanks for debugging it and identifying the root cause of the problem all by yourself! :D

> What is weird though is that in debug/run mode, the project is supposed to compile normally afaik, and not natively.

The project is compiled and run "normally". However, the runtime of your app **is** affected by `<PublishAot>true</PublishAot>`. This behavior is intentional, as the .NET team wanted to prevent users from relying on functionality that works in Debug mode but breaks in the Release version of the app. For more details, see dotnet/runtime#81803.

So, to ensure HotAvalonia works properly, you need to add something like the following to your project file:

```xml
<PropertyGroup Condition="$(DefineConstants.Contains(ENABLE_XAML_HOT_RELOAD))">
    <PublishAot>false</PublishAot>
</PropertyGroup>
```

**Comment by CoRS-Tech** [comment]
Appreciate the clarification.
